// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1S23ZehP-l8KYNIFjEBbZb24Iw5pEC4E',
    appId: '1:416073425879:web:ac1f6845a0e82f51d1e192',
    messagingSenderId: '416073425879',
    projectId: 'chat-app2-staj',
    authDomain: 'chat-app2-staj.firebaseapp.com',
    storageBucket: 'chat-app2-staj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmdKWYg_G-86xTHiOcFHs30TMAgBDjoPw',
    appId: '1:416073425879:android:0110b1a241907605d1e192',
    messagingSenderId: '416073425879',
    projectId: 'chat-app2-staj',
    storageBucket: 'chat-app2-staj.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Yd4WJkgdkV11RotjlmT4s0vJYeA4mv4',
    appId: '1:416073425879:ios:f33430c7e9f48b26d1e192',
    messagingSenderId: '416073425879',
    projectId: 'chat-app2-staj',
    storageBucket: 'chat-app2-staj.firebasestorage.app',
    iosBundleId: 'com.example.stajapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Yd4WJkgdkV11RotjlmT4s0vJYeA4mv4',
    appId: '1:416073425879:ios:f33430c7e9f48b26d1e192',
    messagingSenderId: '416073425879',
    projectId: 'chat-app2-staj',
    storageBucket: 'chat-app2-staj.firebasestorage.app',
    iosBundleId: 'com.example.stajapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1S23ZehP-l8KYNIFjEBbZb24Iw5pEC4E',
    appId: '1:416073425879:web:584fdff7905046efd1e192',
    messagingSenderId: '416073425879',
    projectId: 'chat-app2-staj',
    authDomain: 'chat-app2-staj.firebaseapp.com',
    storageBucket: 'chat-app2-staj.firebasestorage.app',
  );
}
